### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by berot3** [HananoshikaYomaru/obsidian-incomplete-files#14]
Nice plugin! Until now I used tags and checklist for notes I want to finish later. But you plugin seems like a nicer solution! Thanks!

Just wondering what you think about adding support for tags. Adding a #incomplete is maybe a good addition for people working with tags?

**Comment by HananoshikaYomaru** [comment]
@berot3 I already have an issue for this so I mark this as duplicate. see #5.

**Comment by berot3** [comment]
Thank you
